// scripts/preview.js — `npm run preview`. Renders every theme (demo +
// offline) into previews/ and writes a gallery page so you can eyeball
// your theme before opening a PR:
//
//   npm run preview && start previews/index.html      (Windows)
//   npm run preview && open previews/index.html       (macOS)

import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { themes } from "../themes/index.js";
import { renderCard, DEMO_STATUS } from "../lib/card.js";

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "previews");
mkdirSync(out, { recursive: true });

const cards = [];
for (const [name, t] of Object.entries(themes)) {
  writeFileSync(join(out, `${name}.svg`), renderCard(DEMO_STATUS(), t));
  writeFileSync(join(out, `${name}-offline.svg`), renderCard({ ts: 0 }, t));
  cards.push({ name, label: t.label || name, author: t.author || "", description: t.description || "" });
  console.log(`  ${name}.svg + ${name}-offline.svg`);
}

writeFileSync(join(out, "index.html"), `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>presence — theme gallery</title>
<style>
  body{background:#0d0f14;color:#dde3ee;font-family:ui-monospace,Consolas,monospace;
    margin:0;padding:40px 24px}
  h1{font-size:18px;letter-spacing:2px;margin:0 0 6px}
  p.sub{color:#6b7385;margin:0 0 30px;font-size:12px}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(580px,1fr));gap:34px;max-width:1240px;margin:0 auto}
  figure{margin:0}
  img{width:100%;max-width:560px;display:block;border-radius:10px}
  figcaption{margin-top:8px;font-size:12px;color:#9aa3b5}
  figcaption b{color:#dde3ee}
  figcaption i{color:#6b7385}
  label{font-size:11px;color:#6b7385;letter-spacing:1px;cursor:pointer;user-select:none}
</style></head><body>
<h1>presence · theme gallery</h1>
<p class="sub">${cards.length} themes — generated by scripts/preview.js ·
  <label><input type="checkbox" id="off"> show offline state</label></p>
<div class="grid">
${cards.map((c) => `  <figure>
    <img data-on="${c.name}.svg" data-off="${c.name}-offline.svg" src="${c.name}.svg" alt="${c.label}">
    <figcaption><b>${c.label}</b> · ${c.description} — <i>${c.author}</i></figcaption>
  </figure>`).join("\n")}
</div>
<script>
  document.getElementById("off").addEventListener("change", (e) => {
    document.querySelectorAll("img[data-on]").forEach((img) =>
      img.src = e.target.checked ? img.dataset.off : img.dataset.on);
  });
</script>
</body></html>`);

console.log(`\n✓ gallery: ${join(out, "index.html")}`);
